### PR TITLE
[DOCS]: removed one of the double lines after the first heading

### PR DESCRIPTION
**Pull request by Pragya2056**
The issue #38 was worked on.

### CODE REVIEW

**Comment by Pragya2056** [comment]
@IIvexII 
Please review this.

**Review by IIvexII — APPROVED** [review]
LGTM :tada:

**Comment by IIvexII** [comment]
Thanks for contributing. Can you look through the docs and open issue if you can improve something?

**Comment by Pragya2056** [comment]
> Thanks for contributing. Can you look through the docs and open issue if you can improve something?

sure I will look at it.

**Pull request merged**
