### PR TITLE
Add mongodb to README.db

### PR DESCRIPTION
**Pull request by acuriouspickle**
Add mongodb (with logo) to README.db

Change Credits to Technologies

### CODE REVIEW

**Review by IIvexII — CHANGES_REQUESTED** [review]
You forgot to add mongoose and Axios images. Please add them so that I can merge this pull request. Thanks!

**Comment by acuriouspickle** [comment]
I am COMPLETELY new to GitHub, so I apologized if I breached any etiquette! I was not sure what format was acceptable for the images given that I couldn’t locate them on the same sources you were already using, so I only added MongoDB and changed Credits to Technologies. 

If you can help me understand what image services are acceptable (such as, can I just pull the ACIOS tech image off their own web page? I don’t know if it will scale) I’ll go back and add them. 

Thank you!

**Comment by IIvexII** [comment]
@acuriouspickle You can get the images from their website, if the images are in svg then please convert them in into png or jpg first then directly paste them in Github editor it will automatically upload it and provide the url. If the size does not match then add width and height attribute to img tag.

**Comment by acuriouspickle** [comment]
I’ll get on this tomorrow first thing! Thanks for the tips.

**Comment by IIvexII** [comment]
I have uploaded the mongoose image for you. just add the link.
https://user-images.githubusercontent.com/41378765/203491947-b882beeb-22cc-4a34-84fa-c5d0eaad6066.png

**Review by IIvexII — CHANGES_REQUESTED** [review]
Please delete mongoose.svg file and use the link I have given to you to add this image.

**Comment by acuriouspickle** [comment]
Thank you, I was struggling with how to manage the image. I just got this message and will make the change now.

**Comment by IIvexII** [comment]
> I feel like a bull in a china shop here, so feel free to give me guidance or reject my pull requests. I'm an absolute beginner at GitHub!

No issue at all. This is the way we learn. Don't be disappointed, the issue you are working on is solved by @colindaviddick. You can see those changes he made via this 5fd5eb44eac3bdf68d2ff746a027785f4976d36e

**Comment by acuriouspickle** [comment]
You are so kind. Thank you for making the learning process less intimidating.

**Pull request closed without merging**
