### PR TITLE
feat: add Firebase as an alternative to Mongodb

### PR DESCRIPTION
**Pull request by Zain-ul-din**

### CODE REVIEW

**Review by IIvexII — COMMENTED** [review]
I appreciate your idea of replacing mongoDB with firebase. But can you please explain a friendly question, ***what is the motivation behind that?***

**Comment by Zain-ul-din** [comment]
first of all, firebase is very fast you cloud use firebase directly in the front end without interacting with the backend.
Even though, We cloud scrap data on the local machine without deploying anywhere.

Apart from that, firebase also provides ML and analytics kits which may help us in the future. We cloud also do lots of cool stuff with firebase like cloud functions that can run automatically at a certain time.

**Comment by IIvexII** [comment]
> first of all, firebase is very fast you cloud use firebase directly in the front end without interacting with the backend. Even though, We cloud scrap data on the local machine without deploying anywhere.
> 
> Apart from that, firebase also provides ML and analytics kits which may help us in the future. We cloud also do lots of cool stuff with firebase like cloud functions that can run automatically at a certain time.

Thanks for replying @Zain-ul-din! I am curious to know if it provides secure, restricted APIs (read-only) that we can provide directly to the user without explicitly adding our server between them.

**Comment by Zain-ul-din** [comment]
firebase is very curious about security. you cloud write you're own security rules.

image

**Comment by IIvexII** [comment]
> firebase is very curious about security. you cloud write you're own security rules.
> 
> image

Okay! Let's add this then. :+1:

**Comment by Zain-ul-din** [comment]
sure

**Pull request closed without merging**
